language: php
php:
  - '7.0'
services:
  - mysql
before_script:
  - mysql -e 'create database projeto;'
script: 
  - phpunit AutenticaTest.php
  - phpunit CriarContaTest.php
  - phpunit DeletarTest.php
